### ISSUE TITLE
Keine Grafiken wenn shortcode gerendert wird

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-qbank_nocorrectanswer#2]
Habe diese Shortcodes getested und es fehlen die Grafiken:

![Screenshot 2024-07-01 at 23-26-46 Testkurs Simulationen med2uni-elearning de](https://github.com/Wunderbyte-GmbH/moodle-qbank_nocorrectanswer/assets/1620975/41f3ff5d-262c-4ae9-a68b-0df8b6db0aa1)

 [performanceoverview cmid=172] [resultoverview cmid=172] 

Shortcodes wurden auf einer Textseite eingebunden.

**Comment by WunderJacob** [comment]
CSS wurde jetzt richtig eingebunden

**Comment by WunderJacob** [comment]
CSS wurde jetzt richtig eingebunden
